// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPsSmUjY57wjEPpSPRw3TpBV2HT1fTNaQ',
    appId: '1:375467186411:web:abf5148776c4a3243ac6ae',
    messagingSenderId: '375467186411',
    projectId: 'chat-appp-e1a0c',
    authDomain: 'chat-appp-e1a0c.firebaseapp.com',
    storageBucket: 'chat-appp-e1a0c.firebasestorage.app',
    measurementId: 'G-7L476QBCZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYfrfKs31IpuReiRFJsmcy2S716WS-U4s',
    appId: '1:375467186411:android:fa4988c682323bf23ac6ae',
    messagingSenderId: '375467186411',
    projectId: 'chat-appp-e1a0c',
    storageBucket: 'chat-appp-e1a0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iLyx7JXhCi0ZzVqHTYR05olnHDhzTPo',
    appId: '1:375467186411:ios:7dcc200b61ebd3d63ac6ae',
    messagingSenderId: '375467186411',
    projectId: 'chat-appp-e1a0c',
    storageBucket: 'chat-appp-e1a0c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPsSmUjY57wjEPpSPRw3TpBV2HT1fTNaQ',
    appId: '1:375467186411:web:7422f42ec49289f63ac6ae',
    messagingSenderId: '375467186411',
    projectId: 'chat-appp-e1a0c',
    authDomain: 'chat-appp-e1a0c.firebaseapp.com',
    storageBucket: 'chat-appp-e1a0c.firebasestorage.app',
    measurementId: 'G-5R0B0N4Q8Q',
  );
}
